name: Continuous Deployment

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 🔧 Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: 🚧 Install Node dependencies
      run: cd client/web && npm install

    - name: 👷 Build Graphite web client
      run: cd client/web && npm run build

    - name: 🚀 Deploy web client
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: deploy
        folder: client/web/dist
        single-commit: true
        git-config-name: GitHub Actions
